dataAnalise/urls.py
from django.urls import path

from .views import StatisticView, GutenbergRichterView, QuakeMapView, HazardView

urlpatterns = [
    path('', StatisticView.as_view(), name='statistic'),
    path('rozklad-gutenberga-richtera', GutenbergRichterView.as_view(), name='gutenberg-richter'),
    path('hazard-sejsmiczny', HazardView.as_view(), name='seismic-hazard'),
    path('mapa', QuakeMapView.as_view(), name='quake-map'),
]

localQuakes/urls.py
from django.urls import path

# from . import views
from django.views.generic import TemplateView

from .views import quakes_list

from .views import LocalQuakeDetailView

urlpatterns = [
    path('', quakes_list, name='list'),
    path('wstrzas-lokalny-id-<int:pk>/', LocalQuakeDetailView.as_view(), name='detail'),
]

pages/urls.py
from django.urls import path

from .views import HomeView, AboutView, ContactView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('o-projekcie', AboutView.as_view(), name='about'),
    path('kontakt', ContactView.as_view(), name='contact'),
]

sejsmo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.views.generic import TemplateView
from stations.views import StationDetailView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('pages.urls', 'pages'), namespace='pages')),
    path('katalog-lokalny/', include(('localQuakes.urls', 'localQuakes'), namespace='localQuakes')),
    path('katalog-globalny/', include(('globalQuakes.urls', 'globalQuakes'), namespace='globalQuakes')),
    path('analiza-danych/', include(('dataAnalise.urls', 'dataAnalise'), namespace='dataAnalise')),
    path('stacja/<slug:slug>/', StationDetailView.as_view(), name='stationDetail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dataAnalise/models.py
from django.db import models

# Create your models here.

dataAnalise/forms.py
from django import forms

class InputDataForAnalysis(forms.Form):
    deltaT = forms.IntegerField(label='Przedział czasu (w miesiącach)', min_value=1)
    mth = forms.FloatField(label='Magnituda teoretyczna', max_value=5, min_value=2)

dataAnalise/views.py
from django.shortcuts import render

import plotly.offline as opy
import plotly.graph_objs as go

import operator
import collections
from itertools import accumulate
import statistics
import math

from django.views.generic import TemplateView, ListView
from localQuakes.models import LocalQuake

from dataAnalise.forms import InputDataForAnalysis

from django.db.models.functions import TruncMonth
from django.db.models import Count


class StatisticView(TemplateView):
    template_name = "statistic.html"

    # allMonths = LocalQuake.objects.annotate(month=TruncMonth('timestamp')).values('month').annotate(c=Count('id')).values('month', 'c')

    def get_context_data(self, **kwargs):
        context = super(StatisticView, self).get_context_data(**kwargs)

        allMagnitudes = [LocalQuake.magnitude for LocalQuake in LocalQuake.objects.all()]
        allCities = [LocalQuake.city for LocalQuake in LocalQuake.objects.all()]
        allMonths = [LocalQuake.eventDate for LocalQuake in LocalQuake.objects.all()]

        timeRange = subList(allMonths)
        avgTimeRange = statistics.mean(timeRange)


        context['histogramMag'] = renderHistogram(allMagnitudes, 'Histogram magnitud dla wstrząsów lokalnych', 'Magnituda lokalna ML', 'Częstość N')
        context['histogramCity'] = renderHistogram(allCities, 'Ilość wstrząsów w poszczególnych miastach', 'Miasto', 'Liczba wstrząsów')
        context['allMonths'] = renderHistogram(allMonths, 'Ilość wstrząsów w poszczególnych miesiącach', 'Miesiąc', 'Liczba wstrząsów', 20)
        context['timeRange'] = renderHistogram(timeRange, 'Histogram rozkładu odstępów czasowych', 'Czas [godziny]', 'Liczba wstrząsów', 80)
        context['avgTimeRange'] = float("{0:.2f}".format(avgTimeRange))

        return context


class QuakeMapView(TemplateView):
    template_name = "all-quakes-map.html"

    def get_context_data(self, **kwargs):
        context = super(QuakeMapView, self).get_context_data(**kwargs)
        context['last_quakes'] = LocalQuake.objects.all()
        return context



class GutenbergRichterView(TemplateView):
    template_name = 'gutenberg-richter.html'

    def get_context_data(self, **kwargs):
        context = super(GutenbergRichterView, self).get_context_data(**kwargs)

        allMagnitudes = [LocalQuake.magnitude for LocalQuake in LocalQuake.objects.all()]
        allMagnitudesFloat = [float(i) for i in allMagnitudes]
        counter = collections.Counter(allMagnitudesFloat)


        # Histogram normalny
        xnorlam = [float(i) for i in counter.keys()]
        ynormal = [float(i) for i in counter.values()]

        context['allMagnitudes'] = allMagnitudes
        context['histNormal'] = renderBarChart(xnorlam, ynormal, 'Histogram wstrząsów lokalnych', 'Magnituda lokalna ML', 'Częstość N')

        ##########################
        # Histogram zlogarytmowany

        logy = [math.log10(element) for element in ynormal]
        context['histLogy'] = renderBarChart(xnorlam, logy, 'Histogram wstrząsów lokalnych', 'Magnituda lokalna ML', 'Log(N)')

        ##########################
        # Histogram obcięty

        magMin = max(counter.items(), key=operator.itemgetter(1))[0]
        magMax = float("{0:.2f}".format(2*max(xnorlam) - sorted(xnorlam)[-2] ))

        cutCatalogMag = {k: v for k, v in counter.items() if k >= magMin}

        orderDict = collections.OrderedDict(sorted(cutCatalogMag.items()))
        sortcutCatalogMag = dict(orderDict)

        xCut = [float(i) for i in sortcutCatalogMag.keys()]
        yCut = [float(i) for i in sortcutCatalogMag.values()]

        yCut = list(map(int, yCut))
        logyCut = [math.log10(element) for element in yCut]

        context['histCut'] = renderBarChart(xCut, logyCut, 'Obcięty histogram wstrząsów lokalnych', 'Magnituda lokalna ML', 'Log(N)')
        context['magMin'] = magMin
        context['magMax'] = magMax


        ##########################
        # Wykres Logy skumulowany

        yCumulative = list(accumulate((yCut[::-1])))[::-1]
        logyCumulative = [math.log10(element) for element in yCumulative]


        ##########################
        # Metoda największej wiarygodności

        cutMagnitudeList = [i for i in allMagnitudesFloat if i >= magMin]

        magAvg = statistics.mean(cutMagnitudeList)
        magStaDev = statistics.stdev(xCut)
        b = math.log10(math.e) / (magAvg - magMin)
        delb = 2.3 * b ** 2 * magStaDev

        a = []
        for y, x in zip(logyCumulative, xCut):
            z = y + (b*x)
            a.append(z)

        aAvg = statistics.mean(a)
        dela = statistics.stdev(a)

        regliny = []
        for x in xCut:
            z = aAvg + (-b*x)
            regliny.append(z)

        dataCumulative = [go.Bar(
            x=xCut,
            y=logyCumulative,
            marker=dict(
                color='#00a651'
            ),
            name='Skumulowana liczba wstrząsów Nsk'
        ), go.Scatter(
            x=xCut,
            y=regliny,
            marker=dict(
                color='blue'
            ),
            name='Dopasowana linia metodą największej wiarygodności',

        )]

        layoutCumulative = go.Layout(title="Wykres dla N będących skumulowaną liczbą wstrząsów [Nsk] ",
                                     xaxis={'title': 'Magnituda lokalna ML'},
                                     yaxis={'title': 'Log(Nsk)'},
                                     )
        figureCumulative = go.Figure(data=dataCumulative, layout=layoutCumulative)
        divCumulative = opy.plot(figureCumulative, auto_open=False, output_type='div')
        context['chartRegLine'] = divCumulative


        context['magAvg'] = float("{0:.3f}".format(magAvg))
        context['magStaDev'] = float("{0:.3f}".format(magStaDev))
        context['b'] = float("{0:.3f}".format(b))
        context['delb'] = float("{0:.3f}".format(delb))
        context['a'] = float("{0:.3f}".format(aAvg))
        context['dela'] = float("{0:.3f}".format(dela))
        return context


class HazardView(TemplateView):
    template_name = 'hazard.html'


    def get(self, request):
        form = InputDataForAnalysis()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = InputDataForAnalysis(request.POST)


        if form.is_valid():
            deltaT = form.cleaned_data['deltaT']
            mth = form.cleaned_data['mth']


        gutRich = GutenbergRichterView().get_context_data()
        btrue = gutRich['b']
        magMin = gutRich['magMin']
        beta = float("{0:.2f}".format(btrue/math.log10(math.e)))
        mthList = [x * 0.02 for x in range(0, 251)] #[0.2, 0.4, 0.6, 0.8, 1.0, 1.2]
        mylambda = len(gutRich['allMagnitudes'])/18

        probabilityList = []
        timeList = []
        probabilityOfMth = float("{0:.2f}".format((1 - math.exp(-(mylambda)*deltaT*math.exp(-beta*(mth-magMin))))*100)) #poprawić lambdę
        timeOfMth = float("{0:.2f}".format(1/((mylambda)*math.exp(-beta*(mth-magMin)))*30))

        for m in mthList:
            r = 1 - math.exp(-(mylambda)*deltaT*math.exp(-beta*(m-magMin))) #poprawić lambdę
            t = 1/((mylambda)*math.exp(-beta*(m-magMin)))*30
            probabilityList.append(r)
            timeList.append(t)



        divProbability =renderScatterChart(mthList, probabilityList, "Prawdopodobieństwo przewyższenia magnitudy dla zadanego przedziału czasu", "Magnituda", "Prawdopodobieństwo")
        divTime = renderScatterChart(mthList, timeList, "Średni czas wystąpienia wstrząsu o danej magnitudzie", "Magnituda", "Czas (w dniach)")

        args = {'form': form, 'deltaT': deltaT, 'mth': mth, 'b': btrue, 'beta': beta, 'magMin': magMin, 'mylambda': mylambda,  'timeOfMth': timeOfMth, 'probabilityOfMth': probabilityOfMth,  'probabilityPlot': divProbability, 'timePlot': divTime}
        return render(request, self.template_name, args)



def renderScatterChart(x, y, title, xtitle, ytitle):

    data = [go.Scatter(
        x=x,
        y=y,
        mode='markers',
        marker=dict(
            color='#00a651'
        ),
    )]
    layout = go.Layout(title=title, xaxis={'title': xtitle}, yaxis={'title': ytitle})
    figure = go.Figure(data=data, layout=layout)
    div = opy.plot(figure, auto_open=False, output_type='div')

    return div



def renderBarChart(x, y, title, xtitle, ytitle):

    data = [go.Bar(
        x=x,
        y=y,
        marker=dict(
            color='#00a651'
        ),
    )]
    layout = go.Layout(title=title, xaxis={'title': xtitle}, yaxis={'title': ytitle})
    figure = go.Figure(data=data, layout=layout)
    div = opy.plot(figure, auto_open=False, output_type='div')

    return div


def renderHistogram(x, title, xtitle, ytitle, nbins = 0):

    data = [go.Histogram(
        x=x,
        marker=dict(
            color='#00a651'
        ),
        nbinsx=nbins,

    )]
    layout = go.Layout(title=title, xaxis={'title': xtitle}, yaxis={'title': ytitle}, autosize=True, bargap=0.1)
    figure = go.Figure(data=data, layout=layout)
    div = opy.plot(figure, auto_open=False, output_type='div')

    return div


def subList(list):

    listWithRanges = []
    list = sorted(list)

    for index in range(len(list)):

        if index < len(list)-2:
            delTime = abs(list[index] - list[index+1])
            delDays = delTime.total_seconds()//3600

            if delDays < 400:
                listWithRanges.append(delDays)


    return listWithRanges

dataAnalise/templates/all-quakes-map.html
{% extends "base.html" %}
{% load static %}


{% block head_title %}Mapa wszystkich wstrząsów{% endblock %}

{% block head_description %}Strona sieci sejsmologicznej UŚ ma za zadanie dostarczenie informacji o wstrząsach
    sejsmicznych zarejestrowanych przez USS UŚ na Grónym Śląsku{% endblock %}

{% block bodyid %}all-quake-map{% endblock %}

{% block image_top %}
    <!--Top Imagine for static pages-->
    <div class="container-fluid nopadding">
        <div class="row nomargin">
            <div class="static-top">
                <img class="img-background" src="{% static 'pages/img/slajdy/kato.jpg' %}" alt="statystyki">

                <h1>MAPA WSTRZĄSÓW</h1>

            </div>
        </div>
    </div>
    <!--END Object top info-->
{% endblock %}


{% block page_content %}

    <main>

        <section id="intro">

            <div class="container">
                <div class="row">
                    <div class="col-md-12">

                        <h3 class="mainHeader mb60">MAPA WSZYSTKICH WSTRZĄSÓW Z KATALOGU LOKALNEGO</h3>

                    </div>

                </div>
            </div>


            <div class="container-fluid mb60">
                <div class="row">
                    <div id="map3"></div>
                </div>
            </div>

        </section>


    </main>

{% endblock %}

{% block javascript %}

     <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA_upCvmfIJ1lQjTrdbaCMT0228fAGq1wI&callback=initMap">
    </script>

 <script>


     var locations = [

         {% for quake in last_quakes %}
             ['{{ quake.city }}', '{{ quake.eventDate|date:"d M Y H:i" }}', '{{ quake.magnitude }}', {{ quake.latitude }}, {{ quake.longitude }}, '{{ quake.get_absolute_url }}', {{ forloop.counter }}],
         {% endfor %}

     ];

     function initMap() {

         var localMap = new google.maps.Map(document.getElementById('map3'), {
             zoom: 10,
             center: silesiaCenter,
             mapTypeId: google.maps.MapTypeId.ROADMAP,
             styles: mapStyle

         });


         var infowindow = new google.maps.InfoWindow();

         var marker, i;
         var markers = [];

         //Markers Local Loop
         for (i = 0; i < locations.length; i++) {
             marker = new google.maps.Marker({
                 position: new google.maps.LatLng(locations[i][3], locations[i][4]),
                 map: localMap,
                 icon: markEvent
             });

             markers.push(marker);

             google.maps.event.addListener(marker, 'click', (function (marker, i) {
                 return function () {
                     infowindow.setContent(
                         '<div class="markerDescription">' +
                         '<strong>Miasto: </strong>' + locations[i][0] + '<br />' +
                         '<strong>Czas: </strong>' + locations[i][1] + '<br />' +
                         '<strong>Magnituda: </strong>' + locations[i][2] + '<br />' +
                         '<a class="text-right" href="' + locations[i][5] + '">Więcej</a>' +
                         '</div>'
                     );


                     infowindow.open(localMap, marker);
                 }
             })(marker, i));
         }


     }


    </script>

{% endblock %}

dataAnalise/templates/gutenberg-richter.html
{% extends "base.html" %}
{% load static %}


{% block head_title %}Rozkład Gutenberga Richtera{% endblock %}

{% block head_description %}Rozkład Gutenberga Richtera dla wstrząsów zarejestrowanych przez USS UŚ{% endblock %}

{% block bodyid %}about{% endblock %}

{% block image_top %}
    <!--Top Imagine for static pages-->
    <div class="container-fluid nopadding">
        <div class="row nomargin">
            <div class="static-top">
                <img class="img-background" src="{% static 'pages/img/slajdy/slide0.jpg' %}" alt="statystyki">

                <h1>Rozkład <BR /> Gutenberga - Richtera</h1>

            </div>
        </div>
    </div>
    <!--END Object top info-->
{% endblock %}




{% block page_content %}

    <main>

        <section id="intro">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">

                        <h3 class="mainHeader">Rozkład Gutenberga - Richtera dla wstrząsów zarejestrowanych przez USS
                            UŚ</h3>

                        <p class="mt20 text-left">Tutaj krok po kroku zobaczysz jak wygląda rozkład Gutenverga Richtera
                            dla zdarzeń zarejestrowanych przez Uczelnianą Sieć Sejsmologiczną Uniwersytetu Śląskiego.
                            Skrypt został tak zaprogramowany, że automatycznie oblicza relację Gutenbera - Richtera dla
                            wszystkich strząsów znajdujących się w <a href="{% url "localQuakes:list" %}"> katalogu
                                lokalnym </a></p>

                        <p class="mt20 mb60 text-left">Prawo Gutenberga – Richtera stosuje się przede wszystkim do
                            prognozowania zagrożeń trzęsień ziemi na danym terenie. Niewątpliwą zaletą stosowania
                            rozkładu G-R jest prostota metody, która wymaga tylko elementarnych i nielicznych obliczeń.
                            Ze względu na małe wymagania dotyczące informacji wejściowej może być znacznie szerzej
                            stosowana jako najprostsza, przybliżona metoda prognozy zagrożenia sejsmicznego.

                            <br /><br />
                            <a href="{% static 'pages/documents/Fizyka-Ziemi- skrypt.pdf' %}#page=6" target="_blank"> Więcej o samej metodzie i sposobie przeprowadzenia obliczeń</a>

                        </p>

                    </div>

                    <div class="col-md-12 mb60">
                        <h4>Histogram wstrząsów</h4>

                        {% if histNormal %}
                            <div>
                                {{ histNormal|safe }}
                            </div>
                        {% endif %}
                    </div>


                    <div class="col-md-12 mb60">
                        <h4>Histogram wstrząsów Log(N) [N - częstość]</h4>

                        {% if histNormal %}
                            <div>
                                {{ histLogy|safe }}
                            </div>
                        {% endif %}
                    </div>

                    <div class="col-md-12 mb60">
                        <h4>Magnituda kompletności</h4>
                        <p class="text-left mt20">

                            Każda sieć sejmologiczna charakteryzuje się pewnym prgiem, poniżej którego stacje badawcze tej sieci nie są zdolne do rejestracji wszystkich wstrząsów sejsmicznych. Część danych o magnitudzie mniejszej niż magnituda kompletności (zwana też magnitudą minimalną) nie jest zarejestrowana przez użądzenia lub personel. Tym samym magnituda kompletności ogranicza, więc rozkład Gutenberga-Richtera od dołu, tworząc tzw. obcięty rozkład Gutenberga - Richtera.
                            <br/><br/>

                            Magnitudę minimalną można wyznaczyć z histogramu (powyżej), poprzez określenie magnitudy o największej liczbie zdarzeń.

                        </p>

                       <h3 class="mt20 text-left">Magnituda kompletności tego katalogu wynosi: <strong> {{ magMin }} </strong> </h3>
                    </div>


                    <div class="col-md-12 mb60">
                        <h4>Magnituda maksymalna</h4>
                        <p class="text-left mt20">

                            Magnituda maksymalna to górna granica magnitud dla określonego rejonu sejsmicznego. Można przyjąć, że jest to największa możliwa magnituda trzęsienia ziemi lub wstrząsu, która może wystąpić na badanym terenie.

                        </p>

                        <h3 class="mt20 text-left">Magnituda maksymalna tego katalogu wynosi: <strong> {{ magMax }} </strong></h3>
                    </div>

                    <div class="col-md-12 mb60">
                        <h4>Histogram wstrząsów Log(N) - od magnitudy kompletności</h4>

                        {% if histCut %}
                            <div>
                                {{ histCut|safe }}
                            </div>
                        {% endif %}

                    </div>

                    <div class="col-md-12 mb60">
                        <h4>Obcięty rozkład G-R parametry</h4>
                        <p class="text-left mt20">


                        </p>

                        <div class="col-md-6 center-block">
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th>Parametr</th>
                                    <th>Wartość</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>Magnituda średnia</td>
                                    <td>{{ magAvg }}</td>
                                </tr>
                                <tr>
                                    <td>Odchylenie stand. magnitudy</td>
                                    <td>{{ magStaDev }}</td>
                                </tr>
                                <tr>
                                    <td>Współczynnik Gutenberga b</td>
                                    <td>{{ b }}</td>
                                </tr>
                                <tr>
                                    <td>Błąd b</td>
                                    <td>{{ delb }}</td>
                                </tr>
                                <tr>
                                    <td>Funkcja liniowa: średnia współczynnika a</td>
                                    <td>{{ a }}</td>
                                </tr>
                                <tr>
                                    <td>Funkcja liniowa: błąd współczynnika a</td>
                                    <td>{{ dela }}</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>

                    </div>


                    <div class="col-md-12 mb60">
                        <h4>Obcięty rozkład G-R wykres </h4>

                        {% if chartRegLine %}
                            <div>
                                {{ chartRegLine|safe }}
                            </div>
                        {% endif %}

                    </div>


                </div>
            </div>
        </section>


        <div class="separator">
            <div class="mask"></div>
        </div>


    </main>

{% endblock %}

{% block javascript %}


{% endblock %}

dataAnalise/templates/statistic.html
{% extends "base.html" %}
{% load static %}


{% block head_title %}Statystyki{% endblock %}

{% block head_description %}Strona sieci sejsmologicznej UŚ ma za zadanie dostarczenie informacji o wstrząsach
    sejsmicznych zarejestrowanych przez USS UŚ na Grónym Śląsku{% endblock %}

{% block bodyid %}about{% endblock %}

{% block image_top %}
    <!--Top Imagine for static pages-->
    <div class="container-fluid nopadding">
        <div class="row nomargin">
            <div class="static-top">
                <img class="img-background" src="{% static 'pages/img/slajdy/slide0.jpg' %}" alt="statystyki">

                <h1>ANALIZA DANYCH</h1>

            </div>
        </div>
    </div>
    <!--END Object top info-->
{% endblock %}




{% block page_content %}

    <main>

        <section id="intro">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">

                        <h3 class="mainHeader">Statystyki zarejestrowanych wstrząsów lokalnych</h3>
                        <p class="mt20 mb60">Tutaj dowiesz się jak wygląda rozkład wstrząsów zaobserwowanych przez sieć.
                            Analiza danych jest zautomatyzowana, dlatego wszystkie dane są aktualne i obejmują cały
                            katalog lokalny.</p>

                    </div>


                    <div>
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs" role="tablist">

                            <li role="presentation" class="active">
                                <a href="#magnitude" aria-controls="magnitud" role="tab" data-toggle="tab">Magnitudy</a>
                            </li>
                            <li role="presentation">
                                <a href="#city" aria-controls="city" role="tab" data-toggle="tab">Miasta</a>
                            </li>
                            <li role="presentation">
                                <a href="#month" aria-controls="month" role="tab" data-toggle="tab">Czas</a>
                            </li>
                            <li role="presentation">
                                <a href="#gr-relation" aria-controls="month" role="tab" data-toggle="tab">Relacja
                                    Gutenberga - Richtera</a>
                            </li>
                            <li role="presentation">
                                <a href="#hazard" aria-controls="month" role="tab" data-toggle="tab">Hazard
                                    sejsmiczny</a>
                            </li>
                            <li role="presentation">
                                <a href="#map" aria-controls="month" role="tab" data-toggle="tab">Mapa wstrząsów</a>
                            </li>

                        </ul>

                        <!-- Tab panes -->
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="magnitude">

                                <p class="mt20 mb20">Histogram magntud przedstawia częstotliwość rejestracji wstrząsu o
                                    danej magnitudzie. Najwięcej zostało zarejestrowanych wstrząsów o magnitudzie
                                    lokalnej 2.5 co świadczy, że próg kompletności katalogu jest na tym poziomie.</p>

                                {% if histogramMag %}
                                    <div>
                                        {{ histogramMag|safe }}
                                    </div>
                                {% endif %}


                            </div>

                            <div role="tabpanel" class="tab-pane active" id="city">

                                <p class="mt20 mb20">Wykres ilości wstrząsów w poszczególnych miastach. Jest to
                                    bezpośrednio zależne z kopalnią, działającą w poszczególnym rejonie.</p>

                                {% if histogramCity %}
                                    <div>
                                        {{ histogramCity|safe }}
                                    </div>
                                {% endif %}


                            </div>
                            <div role="tabpanel" class="tab-pane active" id="month">

                                {% if allMonths %}
                                    <div>
                                        {{ allMonths|safe }}
                                    </div>
                                {% endif %}

                                <br/><br/><br/>


                                {% if timeRange %}
                                    <div>
                                        {{ timeRange|safe }}
                                    </div>
                                {% endif %}

                            <br/><br/>

                            <p>Średni czas pomiędzy wstrząsami: {{ avgTimeRange }}</p>



                            </div>


                            <div role="tabpanel" class="tab-pane" id="gr-relation">

                                <p class="mt20 mb20">
                                    Prawo Gutenberga – Richtera stosuje się przede wszystkim do prognozowania zagrożeń
                                    trzęsień ziemi na danym terenie.
                                    <br/><br/>
                                    <a href="{% url "dataAnalise:gutenberg-richter" %}">Przejdź do analizy relacji
                                        Gutenberga - Richtera</a>
                                </p>

                            </div>


                            <div role="tabpanel" class="tab-pane" id="hazard">

                                 <p class="mt20 mb20">
                                    Hazard sejsmiczny to prawdopodobieństwo wystąpienia zjawiska fizycznego związanego z trzęsieniem Ziemi (takich jak drgania podłoża, fala tsunami, upłynnienie podłoża, lawiny itd.)
                                    <br/><br/>
                                    <a href="{% url "dataAnalise:seismic-hazard" %}">Przejdź do analizy stacjonarnego hazardu sejsmicznego</a>
                                </p>

                            </div>

                            <div role="tabpanel" class="tab-pane" id="map">


                                 <p class="mt20 mb20">Mapa wszystkich wstrząsów z katalogu lokalnego
                                <br/><br/>
                                <a href="{% url "dataAnalise:quake-map" %}">Przejdź do mapy</a>


                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </section>


        <div class="separator">
            <div class="mask"></div>
        </div>


    </main>

{% endblock %}

{% block javascript %}


    <script>


        $(document).ready(function () {

            $('#city, #month').removeClass('active');

        });


    </script>



{% endblock %}