dataAnalise/urls.py
from django.urls import path

from .views import StatisticView, GutenbergRichterView, QuakeMapView, HazardView

urlpatterns = [
    path('', StatisticView.as_view(), name='statistic'),
    path('rozklad-gutenberga-richtera', GutenbergRichterView.as_view(), name='gutenberg-richter'),
    path('hazard-sejsmiczny', HazardView.as_view(), name='seismic-hazard'),
    path('mapa', QuakeMapView.as_view(), name='quake-map'),
]

localQuakes/urls.py
from django.urls import path

# from . import views
from django.views.generic import TemplateView

from .views import quakes_list

from .views import LocalQuakeDetailView

urlpatterns = [
    path('', quakes_list, name='list'),
    path('wstrzas-lokalny-id-<int:pk>/', LocalQuakeDetailView.as_view(), name='detail'),
]

pages/urls.py
from django.urls import path

from .views import HomeView, AboutView, ContactView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('o-projekcie', AboutView.as_view(), name='about'),
    path('kontakt', ContactView.as_view(), name='contact'),
]

sejsmo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.views.generic import TemplateView
from stations.views import StationDetailView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('pages.urls', 'pages'), namespace='pages')),
    path('katalog-lokalny/', include(('localQuakes.urls', 'localQuakes'), namespace='localQuakes')),
    path('katalog-globalny/', include(('globalQuakes.urls', 'globalQuakes'), namespace='globalQuakes')),
    path('analiza-danych/', include(('dataAnalise.urls', 'dataAnalise'), namespace='dataAnalise')),
    path('stacja/<slug:slug>/', StationDetailView.as_view(), name='stationDetail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8"/>
    <title>{% block head_title %}{% endblock %} | USS UŚ</title>
    <meta name="description" content="{% block head_description  %} {% endblock %}"/>
    <meta name="keywords" content="Sieć Sejsmologiczna, wstrząs, trzęsienie ziemi"/>

    <meta http-equiv="X-UA-Compatible" content="IE=edge.chrome=1"/>
    <meta name="author" content="Robert Saternus">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href='http://fonts.googleapis.com/css?family=Pragati+Narrow:700,400&subset=latin,latin-ext' rel='stylesheet'
          type='text/css'>
    <!--<link rel="shortcut icon" href="img/favicon.ico" type="image/icon">-->

    {% load static %}

    {% block stylesheets  %}
        <link rel="stylesheet" type="text/css" href="{% static 'pages/css/html5reset-1.6.1.css' %}" >
        <link rel="stylesheet" type="text/css" href="{% static 'pages/css/bootstrap.min.css' %}" >
        <link rel="stylesheet" type="text/css" href="{% static 'pages/css/font-awesome.min.css' %}" >
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
        <link rel="stylesheet" type="text/css" href="{% static 'pages/css/style_main.css' %}" >
        <link rel="stylesheet" type="text/css" href="{% static 'pages/css/media-queries.css' %}" >
    {% endblock %}

</head>

<body id="{%block bodyid%}{%endblock%}">

<div id="fb-root"></div>
<script>(function (d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s);
    js.id = id;
    js.src = "//connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.7&appId=603470526483998";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<!--HEADER -->
<header>

    {% include "sticky-header.html" %}

    {% block image_top %}

    {% endblock%}

</header>



{% block page_content %} {% endblock %}


<footer>
    <div class="container">
        <div class="row">
            <div class="col-sm-8 myself">
                <p><strong>Uczelniana Sieć Sejsmologiczna Universytetu Śląskiego</strong> to witryna, która umożliwia
                    gromadzenie oraz analizowanie zjawisk sejsmologicznych pochodzących z działalności górniczej na
                    terenie Górnego Śląska. Jesteś mieszkańcem Śląska? Tutaj możesz sprawdzić, gdzie zatrzęsła się
                    ziemia w Twojej okolicy.
            </div>

            <div class="col-sm-4 nav-footer">
                <div class="col-md-4 hidden-xs hidden-sm ico"><i class="fa fa-question-circle-o" aria-hidden="true"></i>
                </div>
                <div class="col-md-8 col-sm-12 navi">
{#                    <ul>#}
{#                        <li><a href="#">FAQ</a></li>#}
{#                        <li><a href="#">JAK TO DZIAŁA</a></li>#}
{#                        <li><a href="#">O AUTORACH</a></li>#}
{#                        <li><a href="#">KONTAKT</a></li>#}
{#                        <li><a href="#">REGULAMIN</a></li>#}
{#                        <!--<li><a href="#">POLITYKA PRYWATNOŚCI</a></li>-->#}
{#                    </ul>#}
                </div>
            </div>
        </div>
    </div>
    <div class="copyright">&copy; Wykonanie i prowadzenie strony: <a href="http://robertsaternus.pl/">Robert
        Saternus</a></div>
</footer>

<!--SOCIAL MEDIA ICONS-->
<div id="fb-widget">
    <div class="fb-page" data-href="https://www.facebook.com/geofizyka.geologia.uni.slaski" data-tabs="timeline"
         data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
        <blockquote cite="https://www.facebook.com/geofizyka.geologia.uni.slaski" class="fb-xfbml-parse-ignore"><a
                href="https://www.facebook.com/geofizyka.geologia.uni.slaski">FreeLancelot</a></blockquote>
    </div>
    <img class="zakladka" src="{% static 'pages/img/facebook-icon.png' %}" alt="Rankingowiec facebook funpage"/>
</div>


<script>
     var url_event = "{% static 'pages/grafika/event_map_mark.png' %}";
     var url_station = "{% static 'pages/grafika/station_map_mark.png' %}";
</script>

<script src="{% static 'pages/js/jquery-2.1.3.min.js' %}"></script>
<script src="{% static 'pages/js/jquery-ui.min.js' %}"></script>
<script src="{% static 'pages/js/bootstrap.min.js' %}"></script>
<script src="{% static 'pages/js/main.js' %}"></script>



{% block javascript  %}


{% endblock %}

</body>

</html>

templates/sticky-header.html
<!--STICKY BAR-->
    <div id="header-top">
        <div class="burger"><i class="fa fa-caret-square-o-down" aria-hidden="true"></i>MENU</div>
        <div class="traggle-menu">
            <i class="fa fa-times-circle close" aria-hidden="true"></i>

            <div class="logo">
                <h1><a href="{% url "pages:home" %}">USS UŚ<br/></a></h1>
            </div>

            <nav class="mt20">
                <ul>
                    <li><a href="{% url "pages:home" %}"><i class="fa fa-home" aria-hidden="true"></i>HOME</a></li>
                    <li><a href="{% url "pages:about" %}"><i class="fa fa-book" aria-hidden="true"></i>O PROJEKCIE</a></li>
                    <li><a href="{% url "localQuakes:list" %}"><i class="fa fa-database" aria-hidden="true"></i>KAT. LOKALNY</a></li>
                    <li><a href="{% url "globalQuakes:list" %}"><i class="fa fa-globe" aria-hidden="true"></i>KAT. GLOBALNY</a></li>
{#                    <li><a href="#"><i class="fa fa-newspaper-o" aria-hidden="true"></i>AKTUALNOŚCI</a></li>#}
                    <li><a href="{% url "dataAnalise:statistic" %}"><i class="fa fa-question-circle" aria-hidden="true"></i>ANALIZA DANYCH</a></li>
                    <li><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i>KONTAKT</a></li>
                </ul>
            </nav>
        </div>


        <div class="icons-header">
            <ul>
{#                <li><a href="#" data-toggle="modal" data-target="#search-modal"><i class="fa fa-search" aria-hidden="true"></i></a></li>#}
                <li><a href="{% url 'admin:index' %}"><i class="fa fa-user" aria-hidden="true"></i></a></li>
                <li><a href="{% url "pages:home" %}"><i class="fa fa-home" aria-hidden="true"></i></a></li>
            </ul>

        </div>
    </div>
    <!--end sticky bar-->

{#    <!-- Modal with member login -->#}
{#    <div id="login-modal" class="modal fade" role="dialog">#}
{#        <div class="modal-dialog">#}
{##}
{#            <!-- Modal content-->#}
{#            <div class="modal-content">#}
{#                <div class="modal-header">#}
{#                    <button type="button" class="close" data-dismiss="modal">&times;</button>#}
{#                    <h3 class="modal-title">ZALOGUJ SIĘ NA TWOJE KONTO</h3>#}
{#                </div>#}
{#                <div class="modal-body">#}
{#                    <div class="row">#}
{#                        <div class="col-sm-4">#}
{#                            <i class="fa fa-user" aria-hidden="true"></i>#}
{#                        </div>#}
{#                        <div class="col-sm-8">#}
{##}
{#                            <form class="form-horizontal">#}
{#                                <div class="form-group">#}
{#                                    <label for="inputEmail" class="col-xs-3 control-label">Email</label>#}
{#                                    <div class="col-xs-9">#}
{#                                        <input type="email" class="form-control" id="inputEmail" placeholder="Email">#}
{##}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="form-group">#}
{#                                    <label for="inputPassword" class="col-xs-3 control-label">Hasło</label>#}
{#                                    <div class="col-xs-9">#}
{#                                        <input type="password" class="form-control" id="inputPassword"#}
{#                                               placeholder="Hasło">#}
{#                                        <p class="small"><a href="#">Nie pamiętam hasła</a></p>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="form-group">#}
{#                                    <div class="col-xs-offset-1 col-xs-10">#}
{#                                        <div class="checkbox">#}
{#                                            <label>#}
{#                                                <input type="checkbox"> Zapamiętaj mnie#}
{#                                            </label>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="form-group">#}
{#                                    <div class="col-xs-offset-1 col-xs-10">#}
{#                                        <button type="submit" class="btn btn-success btn-lg">Zaloguj</button>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <p class="bad-credential">Niepoprawny login lub hasło</p>#}
{##}
{#                            </form>#}
{##}
{#                        </div>#}
{#                    </div>#}
{##}
{#                    <div class="separator">#}
{#                        <div class="mask"></div>#}
{#                    </div>#}
{##}
{#                    <h6>Nie masz jeszcze konta na stronie?</h6>#}
{#                    <a class="button" href="#"><span>ZAŁÓŻ DARMOWE KONTO</span></a>#}
{#                </div>#}
{##}
{#                <div class="modal-footer">#}
{#                    <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>#}
{#                </div>#}
{#            </div>#}
{##}
{#        </div>#}
{#    </div>#}
{##}
{#    <!-- Modal with searching form -->#}
{#    <div id="search-modal" class="modal fade" role="dialog">#}
{#        <div class="modal-dialog">#}
{##}
{#            <!-- Modal content-->#}
{#            <div class="modal-content">#}
{#                <div class="modal-header">#}
{#                    <button type="button" class="close" data-dismiss="modal">&times;</button>#}
{#                    <h3 class="modal-title">SZUKAJ NA STRONIE</h3>#}
{#                </div>#}
{#                <div class="modal-body">#}
{##}
{#                    <form class="form-inline">#}
{#                        <div class="form-group">#}
{#                            <label class="sr-only" for="search-input">Amount (in dollars)</label>#}
{#                            <div class="input-group">#}
{#                                <div class="input-group-addon"><i class="fa fa-search" aria-hidden="true"></i></div>#}
{#                                <input type="text" class="form-control" id="search-input"#}
{#                                       placeholder="Szukana fraza...">#}
{#                            </div>#}
{#                        </div>#}
{#                        <button type="submit" class="btn btn-success btn-lg">Szukaj</button>#}
{#                    </form>#}
{##}
{#                    <div class="modal-footer">#}
{#                        <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}